version: '3.7'

services:
  mysql-db:
    image: 'mysql:latest'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3306:3306'
    networks:
      - ms-network
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - ./mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: elieta103
      MYSQL_DATABASE: ems

networks:
  ms-network:
    name: ms-network
    driver: bridge